---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  namespace: riju-proxy
  name: riju-proxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: "proxy.{{ .networking.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: riju-proxy
                port:
                  number: 1869
  tls:
    - hosts:
      - "proxy.{{ .networking.domain }}"
      secretName: riju-proxy-tls
