---
kind: Secret
apiVersion: v1
metadata:
  namespace: riju
  name: s3-auth
stringData:
  access-key: "{{ .s3.accessKey }}"
  secret-key: "{{ .s3.secretKey }}"

---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: riju
  name: s3-config
data:
  bucket: "{{ .s3.bucket }}"
  region: "{{ .s3.region }}"
  endpoint: "{{ .s3.endpoint }}"
