---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: riju
  name: minio

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: riju
  name: minio
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - minio-keys
    verbs:
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: riju
  name: minio
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: minio
subjects:
  - kind: ServiceAccount
    name: minio
