---
kind: Secret
apiVersion: v1
metadata:
  namespace: metallb
  name: metallb-memberlist
data:
  secretkey: "{{ .metallb.secretkey | b64enc }}"

---
kind: Secret
apiVersion: v1
metadata:
  namespace: riju
  name: registry-auth
data:
  htpasswd: "{{ .registry.htpasswd | println | b64enc }}"
