---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: traefik
  name: traefik-config
data:
  traefik.yaml: |
    entrypoints:
      traefik:
        address: ":9000/tcp"
      metrics:
        address: ":9100/tcp"
      web:
        address: ":8000/tcp"
      websecure:
        address: ":8443/tcp"
        http:
          tls: true
    api:
      dashboard: true
    ping: true
    metrics:
      prometheus:
        entrypoint: metrics
    providers:
      kubernetescrd: true
      kubernetesingress: true
