global:
  scrape_interval: 15s

scrape_configs:
  - job_name: server
    static_configs:
      - targets: ["localhost:6121"]
  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

remote_write:
  - url: "https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push"
    basic_auth:
      username: "$GRAFANA_PROMETHEUS_USERNAME"
      password: "$GRAFANA_API_KEY"
